---
# Configuration for zellij.

# In order to troubleshoot your configuration try using the following command:
# `zellij setup --check`
# It should show current config locations and features that are enabled.

mouse_mode: false
pane_frames: false

default_mode: locked
keybinds:
    unbind: true
    locked:
        - action: [SwitchToMode: Normal]
          key: [Ctrl: 'g']
    normal:
        - action: [Write: [7], SwitchToMode: Locked]
          key: [Char: 'g']
        - action: [SwitchToMode: Locked]
          key: [Esc, Char: "\n", Char: ' ']
        # - action: [NewPane:, SwitchToMode: Locked]
        - action: [NewPane: Down, SwitchToMode: Locked]
          key: [Char: 'c']
        - action: [NewPane:, SwitchToMode: Locked]
          key: [Char: 'C']
        - action: [NewTab:, SwitchToMode: Locked]
          key: [Char: 't']
        - action: [NewTab:, SwitchToMode: Locked]
          key: [Char: 'T']
        - action: [SwitchToMode: RenameTab, TabNameInput: [0]]
          key: [Char: 'R']
        # - action: [TogglePane]  # not implemented
        #   key: [Char: 'h']
        # - action: [FocusNextPane]
        #   key: [Char: 'r']
        # - action: [ToggleTab, SwitchToMode: Locked]
        #   key: [Char: '-']
        - action: [FocusPreviousPane, SwitchToMode: Locked]
          key: [Ctrl: 'p', Up]
        - action: [FocusNextPane, SwitchToMode: Locked]
          key: [Ctrl: 'n', Down]
        - action: [MoveFocusOrTab: Left, SwitchToMode: Locked]
          key: [Ctrl: 'b', Left]
        - action: [MoveFocusOrTab: Right, SwitchToMode: Locked]
          key: [Ctrl: 'f', Right]
        - action: [MovePane: Up, SwitchToMode: Locked]
          key: [Char: 'P']
        - action: [MovePane: Down, SwitchToMode: Locked]
          key: [Char: 'N']
        - action: [MovePane: Left, SwitchToMode: Locked]
          key: [Char: 'B']
        - action: [MovePane: Right, SwitchToMode: Locked]
          key: [Char: 'F']
        - action: [ToggleFocusFullscreen, SwitchToMode: Locked]
          key: [Char: 'm']
        - action: [ToggleFloatingPanes, SwitchToMode: Locked]
          key: [Char: ' ']
        - action: [TogglePaneEmbedOrFloating, SwitchToMode: Locked]
          key: [Char: 'f']
        - action: [Resize: Increase]
          key: [Char: '=']
        - action: [Resize: Increase]
          key: [Char: '+']
        - action: [Resize: Decrease]
          key: [Char: '-']
        - action: [GoToTab: 1, SwitchToMode: Locked]
          key: [Char: '1']
        - action: [GoToTab: 2, SwitchToMode: Locked]
          key: [Char: '2']
        - action: [GoToTab: 3, SwitchToMode: Locked]
          key: [Char: '3']
        - action: [GoToTab: 4, SwitchToMode: Locked]
          key: [Char: '4']
        - action: [GoToTab: 5, SwitchToMode: Locked]
          key: [Char: '5']
        - action: [GoToTab: 6, SwitchToMode: Locked]
          key: [Char: '6']
        - action: [GoToTab: 7, SwitchToMode: Locked]
          key: [Char: '7']
        - action: [GoToTab: 8, SwitchToMode: Locked]
          key: [Char: '8']
        - action: [GoToTab: 9, SwitchToMode: Locked]
          key: [Char: '9']
        # modes
        - action: [SwitchToMode: Pane]
          key: [Alt: 'p']
        - action: [SwitchToMode: Tab]
          key: [Alt: 't']
        - action: [SwitchToMode: Resize]
          key: [Alt: 'r']
        - action: [SwitchToMode: Scroll]
          key: [Alt: 'S', PageUp:]
        - action: [SwitchToMode: Session]
          key: [Alt: 's']
        - action: [SwitchToMode: Move]
          key: [Alt: 'm']
    pane:
        - action: [SwitchToMode: Normal]
          key: [Ctrl: 'g']
        - action: [SwitchToMode: Locked]
          key: [Esc, Char: "\n", Char: ' ']
        - action: [NewPane: Down]
          key: [Char: 'd']
        - action: [NewPane: Right]
          key: [Char: 'r']
        - action: [CloseFocus]
          key: [Char: 'X']
        - action: [TogglePaneFrames]
          key: [Char: 'Z']
    tab:
        - action: [SwitchToMode: Normal]
          key: [Ctrl: 'g']
        - action: [SwitchToMode: Locked]
          key: [Esc, Char: "\n", Char: ' ']
        - action: [SwitchToMode: RenameTab, TabNameInput: [0]]
          key: [Char: 'r']
        - action: [GoToPreviousTab]
          key: [Ctrl: 'b', Left]
        - action: [GoToNextTab]
          key: [Ctrl: 'f', Right]
        - action: [NewTab: ]
          key: [Char: 'n']
        - action: [CloseTab]
          key: [Char: 'X']
        - action: [ToggleActiveSyncTab]
          key: [Char: 'S']
    renametab:
        - action: [SwitchToMode: Normal]
          key: [Ctrl: 'g']
        - action: [SwitchToMode: Locked]
          key: [Char: "\n"]
        - action: [TabNameInput: [27] , SwitchToMode: Locked]
          key: [Esc]
    resize:
        - action: [SwitchToMode: Normal]
          key: [Ctrl: 'g']
        - action: [SwitchToMode: Locked]
          key: [Esc, Char: "\n", Char: ' ']
        - action: [Resize: Increase]
          key: [Char: '=']
        - action: [Resize: Increase]
          key: [Alt: '+']
        - action: [Resize: Decrease]
          key: [Char: '-']
    scroll:
        - action: [EditScrollback, SwitchToMode: Normal]
          key: [Char: 'e']
        - action: [ScrollToBottom, SwitchToMode: Normal]
        #- action: [SwitchToMode: Normal]
          key: [Ctrl: 'g']
        - action: [SwitchToMode: Locked]
          key: [Esc, Char: "\n", Char: ' ']
        - action: [SwitchToMode: Normal]
          key: [Ctrl: 'r', Ctrl: 's', Char: ' ', Char: "\n"]
        - action: [ScrollDown]
          key: [Ctrl: 'n', Down]
        - action: [ScrollUp]
          key: [Ctrl: 'p', Up]
        - action: [PageScrollDown]
          key: [Ctrl: 'f', PageDown, Right, Char: 'l']
        - action: [PageScrollUp]
          key: [Ctrl: 'b', PageUp, Left, Char: 'h']
        - action: [HalfPageScrollDown]
          key: [Char: 'd']
        - action: [HalfPageScrollUp]
          key: [Char: 'u']
    session:
        - action: [SwitchToMode: Normal]
          key: [Ctrl: 'g']
        - action: [SwitchToMode: Locked]
          key: [Esc, Char: "\n", Char: ' ']
        - action: [Quit]
          key: [Char: 'q']
        - action: [Detach]
          key: [Char: 'd']
    move:
        - action: [SwitchToMode: Normal]
          key: [Ctrl: 'g']
        - action: [SwitchToMode: Locked]
          key: [Esc, Char: "\n", Char: ' ']
        - action: [MovePane: ]
          key: [Char: 'n', Char: "\t"]
        - action: [MovePane: Up]
          key: [Ctrl: 'p', Up]
        - action: [MovePane: Down]
          key: [Ctrl: 'n', Down]
        - action: [MovePane: Left]
          key: [Ctrl: 'b', Left]
        - action: [MovePane: Right]
          key: [Ctrl: 'f', Right]
themes:
  default:
    fg:      245
    bg:      238
    black:   16
    red:     88
    #green:   154
    green:   [70, 130, 180]
    yellow:  0
    blue:    0
    magenta: 0
    cyan:    0
    white:   255
    orange:  166
    gray:    238
