shell = "zsh"
apply = ["defer"]

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
apply = ["source"]
[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"

[plugins.zsh-smartcache]
github = "QuarticCat/zsh-smartcache"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-command-time]
github = "popstas/zsh-command-time"
hooks.post = 'ZSH_COMMAND_TIME_COLOR=008'

[plugins.atuin]
inline = 'zsh-defer smartcache eval atuin init --disable-ctrl-r --disable-up-arrow zsh'

[plugins.mise]
inline = 'zsh-defer smartcache eval mise activate'
