shell = 'zsh'
apply = ['defer']

[templates]
defer = "zsh-defer -c '{{ hooks?.pre | nl }}{% for file in files %}. \"{{ file }}\";{% endfor %}{{ hooks?.post }}'"
fpath_functions = 'fpath=("{{dir}}/functions" $fpath)'  # XXX

[plugins.zsh-defer]
github = 'romkatv/zsh-defer'
apply = ['source']

[plugins.zsh-syntax-highlighting]
github = 'zsh-users/zsh-syntax-highlighting'
hooks.post = '_sheldon-hook-post-zsh-syntax-highlighting'

[plugins.zsh-autosuggestions]
github = 'zsh-users/zsh-autosuggestions'
hooks.post = '_sheldon-hook-post-zsh-autosuggestions'

[plugins.duraiton-info]
github = 'zimfw/duration-info'
apply = ['fpath_functions', 'defer']
hooks.post = '_sheldon-hook-post-duration-info'
