theme = "xia"

[editor]
# rulers = [72]
mouse = false
[editor.cursor-shape]
insert = "bar"
[editor.whitespace.render]
tab = "all"
newline = "all"
[editor.whitespace.characters]
# tabpad = "_"
newline = "↵"

# [lsp]
# display-messages = true

[keys]
# I use non-QWERTY keyboard layout.
# There is no reason why I use h/j/k/l keys to move cursor.

[keys.insert]
C-j = [ "insert_at_line_end", "insert_newline" ]
C-t = [ # transporse-chars of Emacs
  "move_char_left",
  "delete_selection",
  "move_char_left",
  "paste_before",
  "move_char_right"
]

[keys.normal]
h = "no_op"                     # default: move_char_left
j = "no_op"                     # default: move_char_down
k = "no_op"                     # default: move_char_up
l = "no_op"                     # default: move_char_right
Z = "no_op"                     # default: View(sticky) menu

C-x = "no_op"                   # default: decrement
minus = "decrement"
"+" = "increment"

esc = [ "keep_primary_selection", "collapse_selection" ]
C-t = [ # transporse-chars of Emacs
  "collapse_selection",
  "delete_selection",
  "move_char_left",
  "paste_before",
  "move_char_right"
]
C-A-c = [ "yank", "toggle_comments", "paste_after" ]

X = "extend_line_above"         # default: extend_to_line_bounds

  # goto
  [keys.normal.g]
  g = "goto_last_accessed_file" # default: goto_file_start
  e = "no_op"                   # default: goto_last_line
  h = "no_op"                   # default: goto_line_start
  l = "no_op"                   # default: goto_line_end

  lt = "goto_file_start"
  gt = "goto_file_end"

  # match
  [keys.normal.m]
  b = "make_search_word_bounded"

  # view
  [keys.normal.z]
  j = "no_op"                   # default: scroll_down
  k = "no_op"                   # default: scroll_up

  # window
  [keys.normal.space.w]
  h = "no_op"                   # default: jump_view_left
  j = "no_op"                   # default: jump_view_down
  k = "no_op"                   # default: jump_view_up
  l = "no_op"                   # default: jump_view_right
  C-h = "no_op"                 # default: jump_view_left
  C-j = "no_op"                 # default: jump_view_down
  C-k = "no_op"                 # default: jump_view_up
  C-l = "no_op"                 # default: jump_view_right
  n = "hsplit_new"              # default: hsplit_new or vsplit_new menu
  C-n = "hsplit_new"
  [keys.normal.C-w]
  h = "no_op"                   # default: jump_view_left
  j = "no_op"                   # default: jump_view_down
  k = "no_op"                   # default: jump_view_up
  l = "no_op"                   # default: jump_view_right
  C-h = "no_op"                 # default: jump_view_left
  C-j = "no_op"                 # default: jump_view_down
  C-k = "no_op"                 # default: jump_view_up
  C-l = "no_op"                 # default: jump_view_right
  n = "hsplit_new"              # default: hsplit_new or vsplit_new menu
  C-n = "hsplit_new"

[keys.select]
h = "no_op"                     # default: extend_char_left
j = "no_op"                     # default: extend_char_down
k = "no_op"                     # default: extend_char_up
l = "no_op"                     # default: extend_char_right
Z = "no_op"                     # default: View(sticky) menu

v = "collapse_selection"        # default: normal_mode
";" = [                         # default: collapse_selection
  "collapse_selection",
  "normal_mode"
]

X = "extend_line_above"         # default: extend_to_line_bounds

  # goto
  [keys.select.g]
  g = "goto_last_accessed_file" # default: goto_file_start
  e = "no_op"                   # default: goto_last_line
  h = "no_op"                   # default: goto_line_start
  l = "no_op"                   # default: goto_line_end

  lt = "goto_file_start"
  gt = "goto_file_end"

  # match
  [keys.select.m]
  b = "make_search_word_bounded"

  # view
  [keys.select.z]
  j = "no_op"                   # default: scroll_down
  k = "no_op"                   # default: scroll_up

  # window
  [keys.select.space.w]
  h = "no_op"                   # default: jump_view_left
  j = "no_op"                   # default: jump_view_down
  k = "no_op"                   # default: jump_view_up
  l = "no_op"                   # default: jump_view_right
  C-h = "no_op"                 # default: jump_view_left
  C-j = "no_op"                 # default: jump_view_down
  C-k = "no_op"                 # default: jump_view_up
  C-l = "no_op"                 # default: jump_view_right
  n = "hsplit_new"              # default: hsplit_new or vsplit_new menu
  [keys.select.C-w]
  h = "no_op"                   # default: jump_view_left
  j = "no_op"                   # default: jump_view_down
  k = "no_op"                   # default: jump_view_up
  l = "no_op"                   # default: jump_view_right
  C-h = "no_op"                 # default: jump_view_left
  C-j = "no_op"                 # default: jump_view_down
  C-k = "no_op"                 # default: jump_view_up
  C-l = "no_op"                 # default: jump_view_right
  n = "hsplit_new"              # default: hsplit_new or vsplit_new menu
